Revert common caching strategy which was not working at scale

diff --git a/.github/workflows/cjose.yml b/.github/workflows/cjose.yml
--- a/.github/workflows/cjose.yml
+++ b/.github/workflows/cjose.yml
@@ -3,7 +3,7 @@ name: cjose Tests
 # START OF COMMON SECTION
 on:
   push:
-    branches: [ 'master', 'main', 'release/**' ]
+    branches: [ '*' ] # 'master', 'main', 'release/**' ]
   pull_request:
     branches: [ '*' ]
 
@@ -35,6 +35,7 @@ jobs:
         openssl_ref: [ 'openssl-3.5.0' ]
         force_fail: [ 'WOLFPROV_FORCE_FAIL=1', '' ]
     steps:
+      # Checkout the source so we can run the check-workflow-result script
       - name: Checkout wolfProvider
         uses: actions/checkout@v4
         with:
@@ -42,17 +43,13 @@ jobs:
 
       - name: Retrieving wolfProvider from cache
         uses: actions/cache/restore@v4
-        id: wolfprov-cache-restore
+        id: wolfprov-cache
         with:
           path: |
-            scripts
-            wolfssl-source
-            wolfssl-install
-            wolfprov-install
-            openssl-install
-            provider.conf
-
-          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
+            wolfprov-install/lib
+            wolfssl-install/lib
+            openssl-install/lib64
+          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref}}-${{ github.sha }}
           fail-on-cache-miss: true
 
       - name: Install cjose dependencies
@@ -67,13 +64,12 @@ jobs:
           repository: OpenIDC/cjose
           ref: ${{ matrix.cjose_ref }}
           path: cjose
-          fetch-depth: 1
 
       - name: Build cjose
         working-directory: cjose
         run: |
           # Configure with OpenSSL
-          ./configure CFLAGS="-Wno-error=deprecated-declarations" --with-openssl=/git/wolfProvider/openssl-install
+          ./configure  CFLAGS="-Wno-error=deprecated-declarations" --with-openssl=/git/wolfProvider/openssl-install
 
           # Build cjose
           make
@@ -82,8 +78,15 @@ jobs:
         working-directory: cjose
         run: |
           # Set up the environment for wolfProvider
-          source $GITHUB_WORKSPACE/scripts/env-setup
+          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/wolfssl-install/lib:$GITHUB_WORKSPACE/openssl-install/lib64
+          export OPENSSL_CONF=$GITHUB_WORKSPACE/provider.conf
+          export OPENSSL_MODULES=$GITHUB_WORKSPACE/wolfprov-install/lib
           export ${{ matrix.force_fail }}
+          export SHELL=/bin/bash
+
+          echo "Checking OpenSSL providers:"
+          $GITHUB_WORKSPACE/openssl-install/bin/openssl list -providers | tee provider-list.log
+          grep -q libwolfprov provider-list.log || (echo "ERROR: libwolfprov not found in OpenSSL providers" && exit 1)
 
           # Run tests
           make test || true
